"""
Unit tests for proc.py. Classification logic is tested against synthetic
Outcome objects (no process needed); run_cli() itself is tested against
real, trivial system binaries (true/false/sleep/python3) so the
subprocess/timeout/signal plumbing is exercised for real without
depending on qelectrotech being built.
"""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from simulator import env
from simulator.proc import Outcome, run_cli

ASAN_SAMPLE = """\
Some preamble output
=================================================================
==12345==ERROR: AddressSanitizer: heap-use-after-free on address 0x123
    #0 0x1111 in Foo::bar() foo.cpp:42
    #1 0x2222 in main main.cpp:10
=================================================================
"""

QASSERT_SAMPLE = 'Fatal: ASSERT: "!std::isnan(value)" in file /usr/include/x86_64-linux-gnu/qt6/QtCore/qnumeric.h, line 501'


def make_outcome(**kwargs) -> Outcome:
    defaults = dict(
        argv=["x"], returncode=0, signal=None, stdout="", stderr="",
        wall_seconds=0.1, timed_out=False, sandbox_root="/tmp/x",
    )
    defaults.update(kwargs)
    return Outcome(**defaults)


ASAN_REGRESSION_DIR = Path("/home/user/qelectrotech-docker/tests/asan-regression/raw")


class TestClassify(unittest.TestCase):
    def test_clean_exit_is_not_crashed(self):
        o = make_outcome(returncode=0).classify()
        self.assertFalse(o.crashed)

    def test_timeout_is_crashed(self):
        o = make_outcome(timed_out=True, returncode=None).classify()
        self.assertTrue(o.crashed)
        self.assertEqual(o.crash_kind, "timeout")

    def test_negative_returncode_is_signal(self):
        # classify() must be self-contained: derive `signal` from a
        # negative returncode itself, not depend on run_cli (the only
        # normal caller) having already done it -- an Outcome rebuilt
        # from a saved report, or built directly as here, must still
        # classify correctly.
        o = make_outcome(returncode=-11).classify()
        self.assertTrue(o.crashed)
        self.assertEqual(o.crash_kind, "signal")
        self.assertEqual(o.signal, 11)

    def test_asan_output_is_detected(self):
        o = make_outcome(returncode=1, stderr=ASAN_SAMPLE).classify()
        self.assertTrue(o.crashed)
        self.assertEqual(o.crash_kind, "AddressSanitizer")
        self.assertIn("heap-use-after-free", o.crash_message)

    def test_qassert_output_is_detected(self):
        o = make_outcome(returncode=134, stderr=QASSERT_SAMPLE).classify()
        self.assertTrue(o.crashed)
        self.assertEqual(o.crash_kind, "Q_ASSERT")
        self.assertIn("isnan", o.crash_message)

    def test_ordinary_stderr_warning_is_not_a_crash(self):
        o = make_outcome(returncode=0, stderr="qDebug: some ordinary warning\n").classify()
        self.assertFalse(o.crashed)

    def test_to_dict_is_json_safe(self):
        import json
        o = make_outcome(stderr=ASAN_SAMPLE).classify()
        json.dumps(o.to_dict())  # must not raise

    def test_matches_every_real_asan_regression_sample(self):
        # Ground truth: don't trust a hand-written sample string to be an
        # accurate stand-in for what ASan/LSan actually emit. Match
        # against every real .out file already checked in under
        # tests/asan-regression/raw/ (generated by that suite's own run.sh).
        samples = sorted(ASAN_REGRESSION_DIR.glob("*.out")) if ASAN_REGRESSION_DIR.exists() else []
        if not samples:
            self.skipTest(f"no .out samples found under {ASAN_REGRESSION_DIR} "
                           "(run tests/asan-regression/run.sh first)")
        leak_samples = [p for p in samples if "leak" in p.read_text().lower()
                         or "AddressSanitizer" in p.read_text()]
        self.assertTrue(leak_samples, "expected at least one sample containing a real sanitizer report")
        for p in leak_samples:
            text = p.read_text()
            if "ERROR: LeakSanitizer" not in text and "ERROR: AddressSanitizer" not in text:
                continue  # a "*_patched.out" with no leak -- correctly nothing to detect
            with self.subTest(sample=p.name):
                o = make_outcome(returncode=1, stderr=text).classify()
                self.assertTrue(o.crashed, f"{p.name}: real sanitizer output was not detected")


class TestRunCliReal(unittest.TestCase):
    """Exercises the real subprocess path against trivial system binaries."""

    def test_true_exits_clean(self):
        with env.sandbox_context() as sb:
            o = run_cli("/usr/bin/true", [], sb, timeout=5)
        self.assertFalse(o.crashed)
        self.assertEqual(o.returncode, 0)

    def test_false_exits_nonzero_but_not_crashed(self):
        with env.sandbox_context() as sb:
            o = run_cli("/usr/bin/false", [], sb, timeout=5)
        self.assertFalse(o.crashed)
        self.assertEqual(o.returncode, 1)

    def test_timeout_is_enforced(self):
        with env.sandbox_context() as sb:
            o = run_cli("/usr/bin/sleep", ["5"], sb, timeout=0.5)
        self.assertTrue(o.timed_out)
        self.assertTrue(o.crashed)
        self.assertLess(o.wall_seconds, 4.0)  # actually cut short, not left to run

    def test_killed_process_reports_signal(self):
        script = (
            "import os, signal, sys; os.kill(os.getpid(), signal.SIGSEGV)"
        )
        with env.sandbox_context() as sb:
            o = run_cli(sys.executable, ["-c", script], sb, timeout=5)
        self.assertTrue(o.crashed)
        self.assertEqual(o.crash_kind, "signal")
        self.assertEqual(o.signal, 11)  # SIGSEGV

    def test_sandbox_env_is_actually_passed_through(self):
        script = "import os, sys; sys.stdout.write(os.environ.get('HOME', 'MISSING'))"
        with env.sandbox_context() as sb:
            o = run_cli(sys.executable, ["-c", script], sb, timeout=5)
        self.assertEqual(o.stdout.strip(), str(sb.home))


if __name__ == "__main__":
    unittest.main()
